# Generated by Django 3.1.1 on 2020-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200926_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default='property_photo/defaultproperty.jpg', upload_to='property_photo'),
        ),
    ]
